# Generated by Django 2.1.4 on 2018-12-05 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_user_acc_bal'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_acc', models.CharField(max_length=200)),
                ('b_tra', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='acc_bal',
            field=models.IntegerField(max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='acc_det',
            field=models.IntegerField(max_length=200),
        ),
        migrations.AddField(
            model_name='accountdetails',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.User'),
        ),
    ]
