# Generated by Django 2.1.4 on 2018-12-05 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20181205_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='acc_bal',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='acc_det',
            field=models.IntegerField(default=0),
        ),
    ]
