# Generated by Django 2.1.4 on 2018-12-05 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20181205_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountdetails',
            name='Last_Transaction',
            field=models.IntegerField(default=0),
        ),
    ]
