# Generated by Django 2.1.4 on 2018-12-05 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_accountdetails_last_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Last_Transaction', models.CharField(max_length=200)),
                ('Last_Transaction_Date', models.DateTimeField(verbose_name='Last Transaction On')),
            ],
        ),
        migrations.RemoveField(
            model_name='accountdetails',
            name='Last_Transaction',
        ),
        migrations.AddField(
            model_name='transac',
            name='trans',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.AccountDetails'),
        ),
    ]
