# Generated by Django 2.1.4 on 2018-12-06 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20181206_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountdetails',
            name='transac',
        ),
        migrations.RemoveField(
            model_name='transac',
            name='trans',
        ),
        migrations.AddField(
            model_name='transac',
            name='transac',
            field=models.ForeignKey(default=1500, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.AccountDetails'),
            preserve_default=False,
        ),
    ]
